### ISSUE TITLE
maybe there is someting wrong in the equation in the readme figure 1

### ISSUE THREAD

**Issue by Hiccupwzy** [MzeroMiko/mamba-mini#3]
![image](https://github.com/MzeroMiko/mamba-mini/assets/151977184/fbb4cbef-da24-4515-95fa-1073c3049a31)
Why before this is one sum $\sum$ and in the equation is also sum of $\Delta_i$, maybe it should be
$$\sum_{a}^{b-1} B_i u_i e^{-A(\Delta_i)} \Delta_i$$

Or maybe I'm wrong for understanding, Thank you.

**Comment by Hiccupwzy** [comment]
It's my fault and the author is right!
sorry for disturbing.

**Comment by lambdawill** [comment]
Hi, @Hiccupwzy , I propose some questions on Vmamba repo, I am not sure whether you have the same confusion.
